### ISSUE TITLE
i am getting an exception in chatpage please help

### ISSUE THREAD

**Issue by shivam9865** [ibtesam123/real_chat_flutter#1]
Exception has occurred.
PlatformException (PlatformException(error, java.net.URISyntaxException: Illegal character in scheme name at index 0:  https://firechat-1234.herokuapp.com/, null))

this exception is occurring  for " socketIO.init();"  statement 
please help

**Comment by ibtesam123** [comment]
try removing the /  at the end of the url and put it in the namespac
Eg: socketIO = SocketIOManager().createSocketIO('https://firechat-1234.herokuapp.com','/' );

And also instead of sending data as plain text send it as -> json.encode({'value': textController.text}) 
I will change the later.

**Comment by shivam9865** [comment]
thank you it worked
