### ISSUE TITLE
Send message to specific client

### ISSUE THREAD

**Issue by shivam9865** [ibtesam123/real_chat_flutter#2]
when the data is being sent by one user to another the data is being sent to all the users. cant you make it in such a way that it will send the data to the specified user only.
for example the user will send the receiver user id from the app and the along with the message and then the socket.io will send that message to the specified user id only.

**Comment by ibtesam123** [comment]
Yes you can do so using rooms. Both the users join a particular room and any message that is sent will only be broadcasted in that room. I will be writing a blog on this soon.

**Comment by braysonjohn148** [comment]
How is that done. And please help me, am trying to use my localhost to run the server how can i do that.

App:

> var channel = IOWebSocketChannel.connect("ws://http://192.168.43.203:8080");

app.js

> const app = require('express')()
const http = require('http').createServer(app)

app.get('/', (req, res) => {
    res.send("Node Server is running. Yay!!")
})

http.listen(1234)

**Comment by ibtesam123** [comment]
> How is that done. And please help me, am trying to use my localhost to run the server how can i do that.
> 
> App:
> 
> > var channel = IOWebSocketChannel.connect("ws://http://192.168.43.203:8080");
> 
> app.js
> 
> > const app = require('express')()
> > const http = require('http').createServer(app)
> 
> > app.get('/', (req, res) => {
> 
> > ```
> > res.send("Node Server is running. Yay!!")
> > ```
> 
> > })
> 
> > http.listen(8080)

instead of listen(8080) give the ip address as well like http.listen(8080,'192.168.43.690')
